### ISSUE TITLE
./gradlew assemble fails

### ISSUE THREAD

**Issue by zhangt58** [jvff/pcapac_workshop#1]
Hi, it seems that file ``xterm.css`` is missing, here is the error message:

> * What went wrong:
> Could not list contents of '/home/tong/Programming/learning/git/pcapac_workshop/public/stylesheets/xterm.js/xterm.css'. Couldn't follow symbolic link.

**Comment by jvff** [comment]
Hi! Could you try running the following commands in the root directory of the project:

```
git submodule init
git submodule update
```

And then proceed again with a clean build?

```
./gradlew clean
./gradlew assemble
./gradlew runPlayBinary
```

I suspect that the cause of the problem is the missing submodules. Unfortunately, I don't explain yet what a submodule is in the tutorial, but in summary it's a link between a repository and other repositories it uses or depends on. In this case, there are a couple of Javascript libraries I use, so the first two commands basically tells Git to identify which submodules are present and then download them (clone them inside the Git repository).

If it works, please let me know, and I'll update the documentation to include the initial two steps.

Thanks for the report!

Janito

**Comment by zhangt58** [comment]
It works, really impressive! Thank you Janito. 
Tong

**Comment by jvff** [comment]
Excellent! :)

I added some more information to the README so that the steps become clearer. It's on commit [ed3d63eeff3d101dbb155a86ae452b71b17ebe29](https://github.com/jvff/pcapac_workshop/commit/ed3d63eeff3d101dbb155a86ae452b71b17ebe29).

Thank you for the report!

Janito
